

# This file was *autogenerated* from the file Forward.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001 = Integer(0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0)
Prime_BLS = _sage_const_0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001 
#p = 18446744073709551557
F = GF(Prime_BLS)
varlist = ['m1', 'm2', 'dm1']
P = PolynomialRing(F, names=varlist)
P.inject_variables()
m1, m2, dm1 = P.gens()
a1, a2, b1, b2 = P(_sage_const_1 ), P(_sage_const_3 ), P(_sage_const_2 ), P(_sage_const_4 )

r = _sage_const_5 
C = [[F.random_element() for _ in range(_sage_const_3 )] for _ in range(r)]

def Bricks(x1,x2,x3):
    y1, y2, y3 = P(_sage_const_0 ), P(_sage_const_0 ), P(_sage_const_0 )
    
    y1 = x1**_sage_const_5 
    y2 = x2*(x1**_sage_const_2  + a1*x1 + b1)
    y3 = x3*(x2**_sage_const_2  + a2*x2 + b2)
    return y1, y2, y3

def Concrete(x1,x2,x3,r):
    y1, y2, y3 = P(_sage_const_0 ), P(_sage_const_0 ), P(_sage_const_0 )

    y1 = _sage_const_2 *x1 + x2 + x3 + C[r][_sage_const_0 ]
    y2 = x1 + _sage_const_2 *x2 + x3 + C[r][_sage_const_1 ]
    y3 = x1 + x2 + _sage_const_2 *x3 + C[r][_sage_const_2 ]

    return y1, y2, y3

def GenPoly(m1,m2,dm1):
    # input M1
    x1 = m1
    x2 = m2
    x3 = P(_sage_const_0 )

    xx1 = m1+dm1
    xx2 = m2 - _sage_const_2 *dm1
    xx3 = P(_sage_const_0 )
    
    # input Brick1
    y1 = _sage_const_2 *x1 + x2 + x3 + C[_sage_const_0 ][_sage_const_0 ]
    y2 = x1 + _sage_const_2 *x2 + x3 + C[_sage_const_0 ][_sage_const_1 ]
    y3 = x1 + x2 + _sage_const_2 *x3 + C[_sage_const_0 ][_sage_const_2 ]

    yy1 = _sage_const_2 *xx1 + xx2 + xx3 + C[_sage_const_0 ][_sage_const_0 ]
    yy2 = xx1 + _sage_const_2 *xx2 + xx3 + C[_sage_const_0 ][_sage_const_1 ]
    yy3 = xx1 + xx2 + _sage_const_2 *xx3 + C[_sage_const_0 ][_sage_const_2 ]
    
    # input M2
    z1 = y1**_sage_const_5 
    z2 = y2 * (y1**_sage_const_2  + a1*y1 + b1)
    z3 = y3 * (y2**_sage_const_2  + a2*y2 + b2)

    zz1 = yy1**_sage_const_5 
    zz2 = yy2 * (yy1**_sage_const_2  + a1*yy1 + b1)
    zz3 = yy3 * (yy2**_sage_const_2  + a2*yy2 + b2)
    
    # input Brick2
    t1 = _sage_const_2 *z1 + z2 + z3 + C[_sage_const_1 ][_sage_const_0 ] 
    t2 = z1 + _sage_const_2 *z2 + z3 + C[_sage_const_1 ][_sage_const_1 ] 
    t3 = z1 + z2 + _sage_const_2 *z3 + C[_sage_const_1 ][_sage_const_2 ] 

    tt1 = _sage_const_2 *zz1 + zz2 + zz3 + C[_sage_const_1 ][_sage_const_0 ] 
    tt2 = zz1 + _sage_const_2 *zz2 + zz3 + C[_sage_const_1 ][_sage_const_1 ] 
    tt3 = zz1 + zz2 + _sage_const_2 *zz3 + C[_sage_const_1 ][_sage_const_2 ] 

    s2 = t2 * (t1**_sage_const_2  + a1*t1 + b1) 
    s3 = t3 * (t2**_sage_const_2  + a2*t2 + b2)
    ss2 = tt2 * (tt1**_sage_const_2  + a1*tt1 + b1) 
    ss3 = tt3 * (tt2**_sage_const_2  + a2*tt2 + b2)

    f1 = tt1-t1
    f2 = ss2-s2
    f3 = ss3-s3

#print(f1)
#print(f2)
#print(f3)

    print(f1.degree(),f2.degree(),f3.degree())
    return f1, f2, f3

def GenPolyNew(m1,m2,dm1):
    # input M1
    x1 = m1
    x2 = m2
    x3 = P(_sage_const_0 )

    xx1 = m1+dm1
    xx2 = m2 - _sage_const_2 *dm1
    xx3 = P(_sage_const_0 )
    
    y1, y2, y3 = Concrete(x1, x2, x3, _sage_const_0 )
    yy1,yy2,yy3= Concrete(xx1,xx2,xx3,_sage_const_0 )

    z1, z2, z3 = Bricks(y1, y2, y3)
    zz1,zz2,zz3= Bricks(yy1,yy2,yy3)

    t1, t2, t3 = Concrete(z1, z2, z3, _sage_const_1 )
    tt1,tt2,tt3= Concrete(zz1,zz2,zz3,_sage_const_1 )

    s1, s2, s3 = Bricks(t1, t2, t3)
    ss1,ss2,ss3= Bricks(tt1,tt2,tt3)

    u1, u2, u3 = Concrete(s1, s2, s3, _sage_const_2 )
    uu1,uu2,uu3= Concrete(ss1,ss2,ss3,_sage_const_2 )

    v1, v2, v3 = Bricks(u1, u2, u3)
    vv1,vv2,vv3= Bricks(uu1,uu2,uu3)
    
    f1 = uu1-u1
    f2 = vv2-v2
    f3 = vv3-v3

    print(f1.degree(),f2.degree(),f3.degree())
    return f1,f2,f3

#f1,f2,f3=GenPoly(m1,m2,dm1)
f1,f2,f3=GenPolyNew(m1,m2,dm1)
print(f1, end = ",\n")
print(f2, end = ",\n")
print(f3, end = ",\n")



















